UNPACK:		../UNPACK/unpacker.xml
DIGIT:		../DIGIT/digit_data_e72_20251117.xml
CMAP:		../CMAP/channel_map_e72_20260106.xml
USER:		../USER/User.._e72_tpc_0
HDPRM:		../HDPRM/Hodo.._02293
HDPHC:		../HDPHC/HodoPHC.._02293
DCGEO:		../DCGEO/DCGeom.._e72_20260106
DCTDC:		../DCTDC/DCTdc.._01928
DCDRFT:		../DCDRFT/DCDrift.._01928.root
TPCPRM:         ../TPCPRM/TPC.._0
TPCPOS:        	../TPCPOS/TPCPositionCorrectionMap_0
FLDMAP:		../FLDMAP/ShsFieldMap_20210526_Extrapolated